export const TRAINER_LIST_REQUEST = 'TRAINER_LIST_REQUEST';
export const TRAINER_LIST_SUCCESS= 'TRAINER_LIST_SUCCESS';
export const TRAINER_LIST_FAIL = 'TRAINER_LIST_FAIL';

export const TRAINER_DETAILS_REQUEST = 'TRAINER_DETAILS_REQUEST';
export const TRAINER_DETAILS_SUCCESS= 'TRAINER_DETAILS_SUCCESS';
export const TRAINER_DETAILS_FAIL = 'TRAINER_DETAILS_FAIL';

export const TRAINER_SAVE_REQUEST = 'TRAINER_SAVE_REQUEST';
export const TRAINER_SAVE_SUCCESS = 'TRAINER_SAVE_SUCCESS';
export const TRAINER_SAVE_FAIL = 'TRAINER_SAVE_FAIL';

export const TRAINER_DELETE_REQUEST = 'TRAINER_DELETE_REQUEST';
export const TRAINER_DELETE_SUCCESS = 'TRAINER_DELETE_SUCCESS';
export const TRAINER_DELETE_FAIL = 'TRAINER_DELETE_FAIL'; 