export const TRAINER_LIST_REQUEST = 'TRAINER_LIST_REQUEST';
export const TRAINER_LIST_SUCCESS= 'TRAINER_LIST_SUCCESS';
export const TRAINER_LIST_FAIL = 'TRAINER_LIST_FAIL';

export const TRAINER_DETAILS_REQUEST = 'TRAINER_DETAILS_REQUEST';
export const TRAINER_DETAILS_SUCCESS= 'TRAINER_DETAILS_SUCCESS';
export const TRAINER_DETAILS_FAIL = 'TRAINER_DETAILS_FAIL';

export const TRAINER_SAVE_REQUEST = 'TRAINER_SAVE_REQUEST';
export const TRAINER_SAVE_SUCCESS = 'TRAINER_SAVE_SUCCESS';
export const TRAINER_SAVE_FAIL = 'TRAINER_SAVE_FAIL';

export const TRAINER_DELETE_REQUEST = 'TRAINER_DELETE_REQUEST';
export const TRAINER_DELETE_SUCCESS = 'TRAINER_DELETE_SUCCESS';
export const TRAINER_DELETE_FAIL = 'TRAINER_DELETE_FAIL'; 

export const STAFF_LIST_REQUEST = 'STAFF_LIST_REQUEST';
export const STAFF_LIST_SUCCESS= 'STAFF_LIST_SUCCESS';
export const STAFF_LIST_FAIL = 'STAFF_LIST_FAIL';

export const STAFF_DETAILS_REQUEST = 'STAFF_DETAILS_REQUEST';
export const STAFF_DETAILS_SUCCESS= 'STAFF_DETAILS_SUCCESS';
export const STAFF_DETAILS_FAIL = 'STAFF_DETAILS_FAIL';

export const STAFF_SAVE_REQUEST = 'STAFF_SAVE_REQUEST';
export const STAFF_SAVE_SUCCESS = 'STAFF_SAVE_SUCCESS';
export const STAFF_SAVE_FAIL = 'STAFF_SAVE_FAIL';

export const STAFF_DELETE_REQUEST = 'STAFF_DELETE_REQUEST';
export const STAFF_DELETE_SUCCESS = 'STAFF_DELETE_SUCCESS';
export const STAFF_DELETE_FAIL = 'STAFF_DELETE_FAIL'; 