//trainee
export const TRAINEE_LIST_REQUEST = 'TRAINEE_LIST_REQUEST';
export const TRAINEE_LIST_SUCCESS= 'TRAINEE_LIST_SUCCESS';
export const TRAINEE_LIST_FAIL = 'TRAINEE_LIST_FAIL';

export const TRAINEE_DETAILS_REQUEST = 'TRAINEE_DETAILS_REQUEST';
export const TRAINEE_DETAILS_SUCCESS= 'TRAINEE_DETAILS_SUCCESS';
export const TRAINEE_DETAILS_FAIL = 'TRAINEE_DETAILS_FAIL';

export const TRAINEE_SAVE_REQUEST = 'TRAINEE_SAVE_REQUEST';
export const TRAINEE_SAVE_SUCCESS = 'TRAINEE_SAVE_SUCCESS';
export const TRAINEE_SAVE_FAIL = 'TRAINEE_SAVE_FAIL';

export const TRAINEE_DELETE_REQUEST = 'TRAINEE_DELETE_REQUEST';
export const TRAINEE_DELETE_SUCCESS = 'TRAINEE_DELETE_SUCCESS';
export const TRAINEE_DELETE_FAIL = 'TRAINEE_DELETE_FAIL'; 

//category
export const CATEGORY_LIST_REQUEST = 'CATEGORY_LIST_REQUEST';
export const CATEGORY_LIST_SUCCESS= 'CATEGORY_LIST_SUCCESS';
export const CATEGORY_LIST_FAIL = 'CATEGORY_LIST_FAIL';

export const CATEGORY_DETAILS_REQUEST = 'CATEGORY_DETAILS_REQUEST';
export const CATEGORY_DETAILS_SUCCESS= 'CATEGORY_DETAILS_SUCCESS';
export const CATEGORY_DETAILS_FAIL = 'CATEGORY_DETAILS_FAIL';

export const CATEGORY_SAVE_REQUEST = 'CATEGORY_SAVE_REQUEST';
export const CATEGORY_SAVE_SUCCESS = 'CATEGORY_SAVE_SUCCESS';
export const CATEGORY_SAVE_FAIL = 'CATEGORY_SAVE_FAIL';

export const CATEGORY_DELETE_REQUEST = 'CATEGORY_DELETE_REQUEST';
export const CATEGORY_DELETE_SUCCESS = 'CATEGORY_DELETE_SUCCESS';
export const CATEGORY_DELETE_FAIL = 'CATEGORY_DELETE_FAIL'; 

// Course
export const COURSE_LIST_REQUEST = 'COURSE_LIST_REQUEST';
export const COURSE_LIST_SUCCESS= 'COURSE_LIST_SUCCESS';
export const COURSE_LIST_FAIL = 'COURSE_LIST_FAIL';

export const COURSE_DETAILS_REQUEST = 'COURSE_DETAILS_REQUEST';
export const COURSE_DETAILS_SUCCESS= 'COURSE_DETAILS_SUCCESS';
export const COURSE_DETAILS_FAIL = 'COURSE_DETAILS_FAIL';

export const COURSE_SAVE_REQUEST = 'COURSE_SAVE_REQUEST';
export const COURSE_SAVE_SUCCESS = 'COURSE_SAVE_SUCCESS';
export const COURSE_SAVE_FAIL = 'COURSE_SAVE_FAIL';

export const COURSE_DELETE_REQUEST = 'COURSE_DELETE_REQUEST';
export const COURSE_DELETE_SUCCESS = 'COURSE_DELETE_SUCCESS';
export const COURSE_DELETE_FAIL = 'COURSE_DELETE_FAIL'; 

// Topic
export const TOPIC_LIST_REQUEST = 'TOPIC_LIST_REQUEST';
export const TOPIC_LIST_SUCCESS= 'TOPIC_LIST_SUCCESS';
export const TOPIC_LIST_FAIL = 'TOPIC_LIST_FAIL';

export const TOPIC_DETAILS_REQUEST = 'TOPIC_DETAILS_REQUEST';
export const TOPIC_DETAILS_SUCCESS= 'TOPIC_DETAILS_SUCCESS';
export const TOPIC_DETAILS_FAIL = 'TOPIC_DETAILS_FAIL';

export const TOPIC_SAVE_REQUEST = 'TOPIC_SAVE_REQUEST';
export const TOPIC_SAVE_SUCCESS = 'TOPIC_SAVE_SUCCESS';
export const TOPIC_SAVE_FAIL = 'TOPIC_SAVE_FAIL';

export const TOPIC_DELETE_REQUEST = 'TOPIC_DELETE_REQUEST';
export const TOPIC_DELETE_SUCCESS = 'TOPIC_DELETE_SUCCESS';
export const TOPIC_DELETE_FAIL = 'TOPIC_DELETE_FAIL'; 

//Course catalog
export const COURSE_CATEGORY_REQUEST = 'COURSE_CATEGORY_REQUEST';
export const COURSE_CATEGORY_SUCCESS= 'COURSE_CATEGORY_SUCCESS';
export const COURSE_CATEGORY_FAIL = 'COURSE_CATEGORY_FAIL';
