//trainee
export const TRAINEE_LIST_REQUEST = 'TRAINEE_LIST_REQUEST';
export const TRAINEE_LIST_SUCCESS= 'TRAINEE_LIST_SUCCESS';
export const TRAINEE_LIST_FAIL = 'TRAINEE_LIST_FAIL';

export const TRAINEE_DETAILS_REQUEST = 'TRAINEE_DETAILS_REQUEST';
export const TRAINEE_DETAILS_SUCCESS= 'TRAINEE_DETAILS_SUCCESS';
export const TRAINEE_DETAILS_FAIL = 'TRAINEE_DETAILS_FAIL';

export const TRAINEE_SAVE_REQUEST = 'TRAINEE_SAVE_REQUEST';
export const TRAINEE_SAVE_SUCCESS = 'TRAINEE_SAVE_SUCCESS';
export const TRAINEE_SAVE_FAIL = 'TRAINEE_SAVE_FAIL';

export const TRAINEE_DELETE_REQUEST = 'TRAINEE_DELETE_REQUEST';
export const TRAINEE_DELETE_SUCCESS = 'TRAINEE_DELETE_SUCCESS';
export const TRAINEE_DELETE_FAIL = 'TRAINEE_DELETE_FAIL'; 

//category
export const CATEGORY_LIST_REQUEST = 'CATEGORY_LIST_REQUEST';
export const CATEGORY_LIST_SUCCESS= 'CATEGORY_LIST_SUCCESS';
export const CATEGORY_LIST_FAIL = 'CATEGORY_LIST_FAIL';

export const CATEGORY_DETAILS_REQUEST = 'CATEGORY_DETAILS_REQUEST';
export const CATEGORY_DETAILS_SUCCESS= 'CATEGORY_DETAILS_SUCCESS';
export const CATEGORY_DETAILS_FAIL = 'CATEGORY_DETAILS_FAIL';

export const CATEGORY_SAVE_REQUEST = 'CATEGORY_SAVE_REQUEST';
export const CATEGORY_SAVE_SUCCESS = 'CATEGORY_SAVE_SUCCESS';
export const CATEGORY_SAVE_FAIL = 'CATEGORY_SAVE_FAIL';

export const CATEGORY_DELETE_REQUEST = 'CATEGORY_DELETE_REQUEST';
export const CATEGORY_DELETE_SUCCESS = 'CATEGORY_DELETE_SUCCESS';
export const CATEGORY_DELETE_FAIL = 'CATEGORY_DELETE_FAIL'; 

